project:
  type: website
  output-dir: docs
  
website:
  title: "Jingyi Guan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd

  page-footer:
    left: |
      &copy; Jingyi Guan, 2023<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

